# Use root/example as user/password credentials
version: '3.1'

services:
   db:
      image: mysql:5.6
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
         MYSQL_DATABASE: test
         MYSQL_USER: test
         MYSQL_PASSWORD: test
      ports:
      - 3306:3306

